name: tests

on:
  pull_request

jobs:
  build:
     runs-on: ubuntu-latest
     steps:
       - uses: action/checkout@v2 #get all the codebase into the container
       - run:  npm install && npm run test:ci
